#!/bin/bash
echo .create Bond -L-AN
nmcli con add type bond con-name mb0 ifname mb0 bond.options "mode=802.3ad" ipv4.method=disabled ipv6.method=ignore
echo .create Bond-Slave
nmcli con add type ethernet slave-type bond master mb0 con-name mb0.ens192 ifname ens192 ipv4.method=disabled ipv6.method=ignore

echo .create Bridge
nmcli con add type bridge con-name br-mb0.11 ifname br-mb0.11 ipv4.method=manual ipv6.method=ignore ipv4.addresses=10.190.190.11/24 ipv4.gateway=10.190.190.254
echo .create VLAN-br-Slave
nmcli con add type vlan slave-type bridge master br-mb0.11 con-name mb0.11 ifname mb0.11 dev mb0 id 11 ipv4.method=disabled ipv6.method=ignore

echo .activate -L-AN connections
nmcli con up mb0
nmcli con up mb0.11
nmcli con up br-mb0.11

echo .create Bond *S*AN
nmcli con add type bond con-name sb0 ifname sb0 bond.options "mode=802.3ad" ipv4.method=disabled ipv6.method=ignore
echo .create Bond-Slave
nmcli con add type ethernet slave-type bond master sb0 con-name sb0.ens192 ifname ens192 ipv4.method=disabled ipv6.method=ignore
echo .create VLAN
nmcli con add type vlan con-name sb0.12 ifname sb0.12 dev sb0 id 12 ipv4.method=manual ipv6.method=ignore ipv4.addresses=10.190.190.12/24 ipv4.gateway=10.190.190.254

echo .activate *S*AN connections
nmcli con up sb0
nmcli con up sb0.12


echo .restart NM service
systemctl restart NetworkManager.service
